### ISSUE TITLE
Missing description of page components 

### ISSUE THREAD

**Issue by poi33** [enonic/doc-xp#34]
Documentation is lacking page components.
CMS -> Page Components

- Layout Missing
- Part Missing
- Text Missing
- Image Missing
- Fragment Missing

![image](https://user-images.githubusercontent.com/3340349/59603007-8c3bb580-9108-11e9-961f-55ff5c41782a.png)

**Comment by sigdestad** [comment]
This cannot be considered done IMHO?
https://developer.enonic.com/docs/xp/stable/cms/components

**Comment by hjelmevold** [comment]
It seems like this one has been fixed now, based on what's in production. Apparently there must have been some misunderstanding when this issue was last checked and set status back to In Progress, perhaps the changes were not merged or the doc wasn't built properly. Anyway, I'm setting the status to Done.
